// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {backend} from '../models';
import {project} from '../models';
import {workspace} from '../models';
import {config} from '../models';
import {mcp} from '../models';
import {desktop} from '../models';
import {review} from '../models';

export function AbortMerge():Promise<void>;

export function AbortRebase():Promise<void>;

export function ActiveProjectDir():Promise<string>;

export function AddBookmark(arg1:string,arg2:string,arg3:string):Promise<session.SessionBookmark>;

export function AddWorkDirectory(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AppendToGitignore(arg1:string):Promise<void>;

export function ApplyUpdate():Promise<void>;

export function ArchiveSession(arg1:string):Promise<void>;

export function AttachFiles(arg1:string,arg2:Array<string>):Promise<Array<session.AttachmentInfo>>;

export function CancelGoal(arg1:string,arg2:string):Promise<void>;

export function CancelSessionCompaction(arg1:string):Promise<void>;

export function CancelTask(arg1:string):Promise<void>;

export function CancelUnfinishedTask(arg1:string):Promise<void>;

export function CheckForUpdates():Promise<backend.UpdateInfo>;

export function CheckoutBranch(arg1:string):Promise<void>;

export function CheckoutRemoteBranch(arg1:string):Promise<void>;

export function ClearReview(arg1:string):Promise<void>;

export function ClearReviewComments(arg1:string):Promise<void>;

export function Commit(arg1:string):Promise<string>;

export function CompactSessionContext(arg1:string,arg2:string):Promise<void>;

export function ConfirmExit():Promise<void>;

export function ConfirmGoal(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CreateBranch(arg1:string,arg2:string):Promise<void>;

export function CreateHypothesis(arg1:string,arg2:backend.NewHypothesisCard):Promise<backend.ResearchGraphDTO>;

export function CreateProject(arg1:string,arg2:string):Promise<project.ProjectInfo>;

export function CreateSession():Promise<session.SessionInfo>;

export function CreateTag(arg1:string,arg2:string):Promise<void>;

export function DeleteBookmark(arg1:string,arg2:string):Promise<void>;

export function DeleteBranch(arg1:string,arg2:boolean):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteRemoteBranch(arg1:string,arg2:string):Promise<string>;

export function DeleteRemoteTag(arg1:string,arg2:string):Promise<string>;

export function DeleteResearch(arg1:string,arg2:string):Promise<backend.ResearchStatusDTO>;

export function DeleteReviewComment(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function DeleteWorkDirectory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DisableResearch(arg1:string):Promise<void>;

export function DiscardChanges(arg1:string):Promise<void>;

export function DownloadUpdate():Promise<void>;

export function EmitSessionEvent(arg1:session.Event):Promise<void>;

export function EnableResearch(arg1:string,arg2:string):Promise<backend.ResearchStatusDTO>;

export function Fetch(arg1:string,arg2:Array<string>):Promise<string>;

export function ForkSession(arg1:string):Promise<session.SessionInfo>;

export function GenerateCommitMessage():Promise<string>;

export function GetAttachments(arg1:string):Promise<Array<session.AttachmentInfo>>;

export function GetBlackboardAttachmentMarkdown(arg1:string,arg2:string):Promise<string>;

export function GetBlackboardState(arg1:string):Promise<backend.BlackboardStateResponse>;

export function GetBranchBases():Promise<Array<workspace.BranchBase>>;

export function GetBranches():Promise<Array<workspace.Branch>>;

export function GetCommitDiff(arg1:string):Promise<Array<workspace.ReviewFileDiff>>;

export function GetCommitFiles(arg1:string):Promise<Array<workspace.CommitFile>>;

export function GetCommitFilesBatch(arg1:Array<string>):Promise<Record<string, Array<workspace.CommitFile>>>;

export function GetConfig():Promise<backend.ConfigResponse>;

export function GetCurrentBranch():Promise<workspace.BranchInfo>;

export function GetDiffStat(arg1:string):Promise<workspace.DiffStat>;

export function GetDiffStats():Promise<Record<string, workspace.DiffStat>>;

export function GetFileDiff(arg1:string):Promise<string>;

export function GetFileDiffHunks(arg1:string):Promise<Array<workspace.HunkDiffInfo>>;

export function GetFileIcon(arg1:string):Promise<backend.FileIconResponse>;

export function GetGitHistory(arg1:number,arg2:number):Promise<workspace.GitHistoryPage>;

export function GetGitStatus(arg1:string):Promise<Record<string, workspace.GitStatusEntry>>;

export function GetHardenGitRepos():Promise<Array<string>>;

export function GetLastActiveProjectID():Promise<string>;

export function GetLogLevel():Promise<string>;

export function GetMCPServers():Promise<Record<string, config.MCPServerConfig>>;

export function GetMCPStatus():Promise<Array<mcp.ServerStatus>>;

export function GetModelConfig(arg1:string):Promise<backend.ModelConfigResponse>;

export function GetPendingActions(arg1:string):Promise<desktop.PendingActionsResponse>;

export function GetProjectSwitchState(arg1:string):Promise<backend.ProjectUIStateResponse>;

export function GetProjectUIState(arg1:string):Promise<backend.ProjectUIStateResponse>;

export function GetRebaseMergeState():Promise<workspace.MergeRebaseState>;

export function GetResearchGraph(arg1:string):Promise<backend.ResearchGraphDTO>;

export function GetResearchNextStep(arg1:string,arg2:string):Promise<backend.ResearchNextStepDTO>;

export function GetResearchStatus(arg1:string):Promise<backend.ResearchStatusDTO>;

export function GetReview(arg1:string):Promise<review.Review>;

export function GetReviewDiff():Promise<Array<workspace.ReviewFileDiff>>;

export function GetSecuritySettings():Promise<backend.SecuritySettingsResponse>;

export function GetSessionHistory(arg1:string):Promise<Array<session.ChatMessage>>;

export function GetSessionRuntimeStatus(arg1:string):Promise<session.SessionRuntimeStatus>;

export function GetSessionTokens(arg1:string):Promise<backend.SessionTokensResponse>;

export function GetSessionWorkspace(arg1:string):Promise<string>;

export function GetSmallLLMConfig():Promise<backend.SmallLLMConfigResponse>;

export function GetStepOutput(arg1:string,arg2:string):Promise<string>;

export function GetTerminalHistory(arg1:string):Promise<Array<session.TerminalCommand>>;

export function GetToolList():Promise<Array<backend.ToolInfo>>;

export function GetTrustedGitRepos():Promise<Array<string>>;

export function GetUpdateSettings():Promise<backend.UpdateSettings>;

export function GetVectorIndexStatus():Promise<backend.VectorIndexStatus>;

export function HardenGitRepo(arg1:string):Promise<void>;

export function HasDefaultModel():Promise<boolean>;

export function Lifecycle():Promise<backend.FrontendAPILifecycle>;

export function ListAgents():Promise<Array<backend.AgentDescriptorDTO>>;

export function ListAllSessions():Promise<Array<session.SessionInfo>>;

export function ListBookmarks(arg1:string):Promise<Array<session.SessionBookmark>>;

export function ListDirectory(arg1:string,arg2:boolean):Promise<Array<workspace.FileNode>>;

export function ListProjectWorkDirectories(arg1:string):Promise<Array<project.WorkDirectoryRecord>>;

export function ListProjects():Promise<Array<project.ProjectInfo>>;

export function ListProviderModels(arg1:string):Promise<Array<string>>;

export function ListSessionWorkDirectories(arg1:string):Promise<Array<project.WorkDirectoryRecord>>;

export function ListSessions():Promise<Array<session.SessionInfo>>;

export function ListSkills():Promise<Array<backend.SkillDescriptorDTO>>;

export function Merge(arg1:string):Promise<void>;

export function OptimizePrompt(arg1:string):Promise<backend.OptimizePromptResponse>;

export function PasteFromClipboard(arg1:string,arg2:boolean):Promise<session.PasteResult>;

export function PauseSession(arg1:string):Promise<void>;

export function PersistWindowBounds():Promise<void>;

export function PickAttachmentFiles():Promise<Array<string>>;

export function PickDirectory():Promise<string>;

export function PinSession(arg1:string):Promise<void>;

export function Pull(arg1:string,arg2:Array<string>):Promise<string>;

export function Push(arg1:string,arg2:Array<string>):Promise<string>;

export function PushBranch(arg1:string):Promise<string>;

export function PushTag(arg1:string,arg2:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileAsDataURL(arg1:string):Promise<string>;

export function Rebase(arg1:string):Promise<void>;

export function RemoveAttachment(arg1:string,arg2:string):Promise<void>;

export function RemoveHardenGitRepo(arg1:string):Promise<void>;

export function RemoveTrustedGitRepo(arg1:string):Promise<void>;

export function RenameBookmark(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameBranch(arg1:string,arg2:string):Promise<void>;

export function RenameProject(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ResetToCommit(arg1:string,arg2:string):Promise<void>;

export function ResolvePendingMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<string, any>):Promise<void>;

export function ResumeSession(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ResumeTask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunBackgroundUpdateCheck():Promise<void>;

export function SaveMessageAsMarkdown(arg1:string):Promise<string>;

export function SaveProjectActiveSession(arg1:string,arg2:string):Promise<void>;

export function SaveProjectSwitchState(arg1:backend.ProjectUIStateRequest):Promise<void>;

export function SaveProjectUIState(arg1:backend.ProjectUIStateRequest):Promise<void>;

export function SaveReviewFileComment(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveReviewGeneralComment(arg1:string,arg2:string):Promise<void>;

export function SaveReviewHunkComment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveReviewPrompt(arg1:string):Promise<backend.ReviewPromptMessage>;

export function SearchBlackboardStepOutputs(arg1:string,arg2:string):Promise<Array<string>>;

export function SearchVectorStore(arg1:backend.SearchRequest):Promise<Array<backend.VectorStoreEntry>>;

export function SendMessage(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>,arg5:string,arg6:string,arg7:boolean,arg8:string,arg9:boolean):Promise<void>;

export function SetActiveResearch(arg1:string,arg2:string):Promise<backend.ResearchStatusDTO>;

export function SetHypothesisPinned(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SetLogLevel(arg1:string):Promise<void>;

export function SetModelConfig(arg1:string,arg2:backend.ModelConfigRequest):Promise<void>;

export function SetResearchPinned(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetReviewStatus(arg1:string,arg2:string):Promise<void>;

export function SetUpdateSettings(arg1:boolean):Promise<backend.UpdateSettings>;

export function SetWailsLogger(arg1:desktop.wailsLogAdapter):Promise<void>;

export function SkipVersion(arg1:string):Promise<void>;

export function StageAll():Promise<void>;

export function StageFile(arg1:string):Promise<void>;

export function StartTerminal(arg1:string):Promise<void>;

export function StartTerminalInDir(arg1:string,arg2:string):Promise<void>;

export function StashCreate(arg1:string):Promise<void>;

export function StashDrop(arg1:number):Promise<void>;

export function StashList():Promise<Array<workspace.StashEntry>>;

export function StashPop(arg1:number):Promise<void>;

export function StopTerminal(arg1:string):Promise<void>;

export function SwitchProject(arg1:string):Promise<void>;

export function TerminalInput(arg1:string,arg2:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TrustGitRepo(arg1:string):Promise<void>;

export function UnstageAll():Promise<void>;

export function UnstageFile(arg1:string):Promise<void>;

export function UnwatchDirectory(arg1:string):Promise<void>;

export function UpdateExperimentalFeatures(arg1:boolean):Promise<void>;

export function UpdateHypothesis(arg1:string,arg2:string,arg3:string,arg4:backend.HypothesisUpdateFields):Promise<backend.ResearchGraphDTO>;

export function UpdateLLMConfig(arg1:backend.LLMFullConfigRequest):Promise<void>;

export function UpdateMCPServers(arg1:Record<string, config.MCPServerConfig>):Promise<void>;

export function UpdateProxySettings(arg1:backend.ProxySettingsRequest):Promise<void>;

export function UpdateSearchSettings(arg1:backend.SearchSettingsRequest):Promise<void>;

export function UpdateSecuritySettings(arg1:backend.SecuritySettingsResponse):Promise<void>;

export function UpdateSmallLLMConfig(arg1:backend.SmallLLMConfigResponse):Promise<void>;

export function UpdateWorkDirectoryDescription(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function WatchDirectory(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;
