// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortMerge() {
  return window['go']['desktop']['App']['AbortMerge']();
}

export function AbortRebase() {
  return window['go']['desktop']['App']['AbortRebase']();
}

export function ActiveProjectDir() {
  return window['go']['desktop']['App']['ActiveProjectDir']();
}

export function AddBookmark(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['AddBookmark'](arg1, arg2, arg3);
}

export function AddWorkDirectory(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['AddWorkDirectory'](arg1, arg2, arg3, arg4);
}

export function AppendToGitignore(arg1) {
  return window['go']['desktop']['App']['AppendToGitignore'](arg1);
}

export function ApplyUpdate() {
  return window['go']['desktop']['App']['ApplyUpdate']();
}

export function ArchiveSession(arg1) {
  return window['go']['desktop']['App']['ArchiveSession'](arg1);
}

export function AttachFiles(arg1, arg2) {
  return window['go']['desktop']['App']['AttachFiles'](arg1, arg2);
}

export function CancelGoal(arg1, arg2) {
  return window['go']['desktop']['App']['CancelGoal'](arg1, arg2);
}

export function CancelSessionCompaction(arg1) {
  return window['go']['desktop']['App']['CancelSessionCompaction'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['desktop']['App']['CancelTask'](arg1);
}

export function CancelUnfinishedTask(arg1) {
  return window['go']['desktop']['App']['CancelUnfinishedTask'](arg1);
}

export function CheckForUpdates() {
  return window['go']['desktop']['App']['CheckForUpdates']();
}

export function CheckoutBranch(arg1) {
  return window['go']['desktop']['App']['CheckoutBranch'](arg1);
}

export function CheckoutRemoteBranch(arg1) {
  return window['go']['desktop']['App']['CheckoutRemoteBranch'](arg1);
}

export function ClearReview(arg1) {
  return window['go']['desktop']['App']['ClearReview'](arg1);
}

export function ClearReviewComments(arg1) {
  return window['go']['desktop']['App']['ClearReviewComments'](arg1);
}

export function Commit(arg1) {
  return window['go']['desktop']['App']['Commit'](arg1);
}

export function CompactSessionContext(arg1, arg2) {
  return window['go']['desktop']['App']['CompactSessionContext'](arg1, arg2);
}

export function ConfirmExit() {
  return window['go']['desktop']['App']['ConfirmExit']();
}

export function ConfirmGoal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['App']['ConfirmGoal'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateBranch(arg1, arg2) {
  return window['go']['desktop']['App']['CreateBranch'](arg1, arg2);
}

export function CreateHypothesis(arg1, arg2) {
  return window['go']['desktop']['App']['CreateHypothesis'](arg1, arg2);
}

export function CreateProject(arg1, arg2) {
  return window['go']['desktop']['App']['CreateProject'](arg1, arg2);
}

export function CreateSession() {
  return window['go']['desktop']['App']['CreateSession']();
}

export function CreateTag(arg1, arg2) {
  return window['go']['desktop']['App']['CreateTag'](arg1, arg2);
}

export function DeleteBookmark(arg1, arg2) {
  return window['go']['desktop']['App']['DeleteBookmark'](arg1, arg2);
}

export function DeleteBranch(arg1, arg2) {
  return window['go']['desktop']['App']['DeleteBranch'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['desktop']['App']['DeleteProject'](arg1);
}

export function DeleteRemoteBranch(arg1, arg2) {
  return window['go']['desktop']['App']['DeleteRemoteBranch'](arg1, arg2);
}

export function DeleteRemoteTag(arg1, arg2) {
  return window['go']['desktop']['App']['DeleteRemoteTag'](arg1, arg2);
}

export function DeleteResearch(arg1, arg2) {
  return window['go']['desktop']['App']['DeleteResearch'](arg1, arg2);
}

export function DeleteReviewComment(arg1) {
  return window['go']['desktop']['App']['DeleteReviewComment'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['desktop']['App']['DeleteSession'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['desktop']['App']['DeleteTag'](arg1);
}

export function DeleteWorkDirectory(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['DeleteWorkDirectory'](arg1, arg2, arg3);
}

export function DisableResearch(arg1) {
  return window['go']['desktop']['App']['DisableResearch'](arg1);
}

export function DiscardChanges(arg1) {
  return window['go']['desktop']['App']['DiscardChanges'](arg1);
}

export function DownloadUpdate() {
  return window['go']['desktop']['App']['DownloadUpdate']();
}

export function EmitSessionEvent(arg1) {
  return window['go']['desktop']['App']['EmitSessionEvent'](arg1);
}

export function EnableResearch(arg1, arg2) {
  return window['go']['desktop']['App']['EnableResearch'](arg1, arg2);
}

export function Fetch(arg1, arg2) {
  return window['go']['desktop']['App']['Fetch'](arg1, arg2);
}

export function ForkSession(arg1) {
  return window['go']['desktop']['App']['ForkSession'](arg1);
}

export function GenerateCommitMessage() {
  return window['go']['desktop']['App']['GenerateCommitMessage']();
}

export function GetAttachments(arg1) {
  return window['go']['desktop']['App']['GetAttachments'](arg1);
}

export function GetBlackboardAttachmentMarkdown(arg1, arg2) {
  return window['go']['desktop']['App']['GetBlackboardAttachmentMarkdown'](arg1, arg2);
}

export function GetBlackboardState(arg1) {
  return window['go']['desktop']['App']['GetBlackboardState'](arg1);
}

export function GetBranchBases() {
  return window['go']['desktop']['App']['GetBranchBases']();
}

export function GetBranches() {
  return window['go']['desktop']['App']['GetBranches']();
}

export function GetCommitDiff(arg1) {
  return window['go']['desktop']['App']['GetCommitDiff'](arg1);
}

export function GetCommitFiles(arg1) {
  return window['go']['desktop']['App']['GetCommitFiles'](arg1);
}

export function GetCommitFilesBatch(arg1) {
  return window['go']['desktop']['App']['GetCommitFilesBatch'](arg1);
}

export function GetConfig() {
  return window['go']['desktop']['App']['GetConfig']();
}

export function GetCurrentBranch() {
  return window['go']['desktop']['App']['GetCurrentBranch']();
}

export function GetDiffStat(arg1) {
  return window['go']['desktop']['App']['GetDiffStat'](arg1);
}

export function GetDiffStats() {
  return window['go']['desktop']['App']['GetDiffStats']();
}

export function GetFileDiff(arg1) {
  return window['go']['desktop']['App']['GetFileDiff'](arg1);
}

export function GetFileDiffHunks(arg1) {
  return window['go']['desktop']['App']['GetFileDiffHunks'](arg1);
}

export function GetFileIcon(arg1) {
  return window['go']['desktop']['App']['GetFileIcon'](arg1);
}

export function GetGitHistory(arg1, arg2) {
  return window['go']['desktop']['App']['GetGitHistory'](arg1, arg2);
}

export function GetGitStatus(arg1) {
  return window['go']['desktop']['App']['GetGitStatus'](arg1);
}

export function GetHardenGitRepos() {
  return window['go']['desktop']['App']['GetHardenGitRepos']();
}

export function GetLastActiveProjectID() {
  return window['go']['desktop']['App']['GetLastActiveProjectID']();
}

export function GetLogLevel() {
  return window['go']['desktop']['App']['GetLogLevel']();
}

export function GetMCPServers() {
  return window['go']['desktop']['App']['GetMCPServers']();
}

export function GetMCPStatus() {
  return window['go']['desktop']['App']['GetMCPStatus']();
}

export function GetModelConfig(arg1) {
  return window['go']['desktop']['App']['GetModelConfig'](arg1);
}

export function GetPendingActions(arg1) {
  return window['go']['desktop']['App']['GetPendingActions'](arg1);
}

export function GetProjectSwitchState(arg1) {
  return window['go']['desktop']['App']['GetProjectSwitchState'](arg1);
}

export function GetProjectUIState(arg1) {
  return window['go']['desktop']['App']['GetProjectUIState'](arg1);
}

export function GetRebaseMergeState() {
  return window['go']['desktop']['App']['GetRebaseMergeState']();
}

export function GetResearchGraph(arg1) {
  return window['go']['desktop']['App']['GetResearchGraph'](arg1);
}

export function GetResearchNextStep(arg1, arg2) {
  return window['go']['desktop']['App']['GetResearchNextStep'](arg1, arg2);
}

export function GetResearchStatus(arg1) {
  return window['go']['desktop']['App']['GetResearchStatus'](arg1);
}

export function GetReview(arg1) {
  return window['go']['desktop']['App']['GetReview'](arg1);
}

export function GetReviewDiff() {
  return window['go']['desktop']['App']['GetReviewDiff']();
}

export function GetSecuritySettings() {
  return window['go']['desktop']['App']['GetSecuritySettings']();
}

export function GetSessionHistory(arg1) {
  return window['go']['desktop']['App']['GetSessionHistory'](arg1);
}

export function GetSessionRuntimeStatus(arg1) {
  return window['go']['desktop']['App']['GetSessionRuntimeStatus'](arg1);
}

export function GetSessionTokens(arg1) {
  return window['go']['desktop']['App']['GetSessionTokens'](arg1);
}

export function GetSessionWorkspace(arg1) {
  return window['go']['desktop']['App']['GetSessionWorkspace'](arg1);
}

export function GetSmallLLMConfig() {
  return window['go']['desktop']['App']['GetSmallLLMConfig']();
}

export function GetStepOutput(arg1, arg2) {
  return window['go']['desktop']['App']['GetStepOutput'](arg1, arg2);
}

export function GetTerminalHistory(arg1) {
  return window['go']['desktop']['App']['GetTerminalHistory'](arg1);
}

export function GetToolList() {
  return window['go']['desktop']['App']['GetToolList']();
}

export function GetTrustedGitRepos() {
  return window['go']['desktop']['App']['GetTrustedGitRepos']();
}

export function GetUpdateSettings() {
  return window['go']['desktop']['App']['GetUpdateSettings']();
}

export function GetVectorIndexStatus() {
  return window['go']['desktop']['App']['GetVectorIndexStatus']();
}

export function HardenGitRepo(arg1) {
  return window['go']['desktop']['App']['HardenGitRepo'](arg1);
}

export function HasDefaultModel() {
  return window['go']['desktop']['App']['HasDefaultModel']();
}

export function Lifecycle() {
  return window['go']['desktop']['App']['Lifecycle']();
}

export function ListAgents() {
  return window['go']['desktop']['App']['ListAgents']();
}

export function ListAllSessions() {
  return window['go']['desktop']['App']['ListAllSessions']();
}

export function ListBookmarks(arg1) {
  return window['go']['desktop']['App']['ListBookmarks'](arg1);
}

export function ListDirectory(arg1, arg2) {
  return window['go']['desktop']['App']['ListDirectory'](arg1, arg2);
}

export function ListProjectWorkDirectories(arg1) {
  return window['go']['desktop']['App']['ListProjectWorkDirectories'](arg1);
}

export function ListProjects() {
  return window['go']['desktop']['App']['ListProjects']();
}

export function ListProviderModels(arg1) {
  return window['go']['desktop']['App']['ListProviderModels'](arg1);
}

export function ListSessionWorkDirectories(arg1) {
  return window['go']['desktop']['App']['ListSessionWorkDirectories'](arg1);
}

export function ListSessions() {
  return window['go']['desktop']['App']['ListSessions']();
}

export function ListSkills() {
  return window['go']['desktop']['App']['ListSkills']();
}

export function Merge(arg1) {
  return window['go']['desktop']['App']['Merge'](arg1);
}

export function OptimizePrompt(arg1) {
  return window['go']['desktop']['App']['OptimizePrompt'](arg1);
}

export function PasteFromClipboard(arg1, arg2) {
  return window['go']['desktop']['App']['PasteFromClipboard'](arg1, arg2);
}

export function PauseSession(arg1) {
  return window['go']['desktop']['App']['PauseSession'](arg1);
}

export function PersistWindowBounds() {
  return window['go']['desktop']['App']['PersistWindowBounds']();
}

export function PickAttachmentFiles() {
  return window['go']['desktop']['App']['PickAttachmentFiles']();
}

export function PickDirectory() {
  return window['go']['desktop']['App']['PickDirectory']();
}

export function PinSession(arg1) {
  return window['go']['desktop']['App']['PinSession'](arg1);
}

export function Pull(arg1, arg2) {
  return window['go']['desktop']['App']['Pull'](arg1, arg2);
}

export function Push(arg1, arg2) {
  return window['go']['desktop']['App']['Push'](arg1, arg2);
}

export function PushBranch(arg1) {
  return window['go']['desktop']['App']['PushBranch'](arg1);
}

export function PushTag(arg1, arg2) {
  return window['go']['desktop']['App']['PushTag'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['desktop']['App']['ReadFile'](arg1);
}

export function ReadFileAsDataURL(arg1) {
  return window['go']['desktop']['App']['ReadFileAsDataURL'](arg1);
}

export function Rebase(arg1) {
  return window['go']['desktop']['App']['Rebase'](arg1);
}

export function RemoveAttachment(arg1, arg2) {
  return window['go']['desktop']['App']['RemoveAttachment'](arg1, arg2);
}

export function RemoveHardenGitRepo(arg1) {
  return window['go']['desktop']['App']['RemoveHardenGitRepo'](arg1);
}

export function RemoveTrustedGitRepo(arg1) {
  return window['go']['desktop']['App']['RemoveTrustedGitRepo'](arg1);
}

export function RenameBookmark(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['RenameBookmark'](arg1, arg2, arg3);
}

export function RenameBranch(arg1, arg2) {
  return window['go']['desktop']['App']['RenameBranch'](arg1, arg2);
}

export function RenameProject(arg1, arg2) {
  return window['go']['desktop']['App']['RenameProject'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['desktop']['App']['RenameSession'](arg1, arg2);
}

export function ResetToCommit(arg1, arg2) {
  return window['go']['desktop']['App']['ResetToCommit'](arg1, arg2);
}

export function ResolvePendingMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['App']['ResolvePendingMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function ResumeSession(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['ResumeSession'](arg1, arg2, arg3, arg4);
}

export function ResumeTask(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['ResumeTask'](arg1, arg2, arg3);
}

export function RunBackgroundUpdateCheck() {
  return window['go']['desktop']['App']['RunBackgroundUpdateCheck']();
}

export function SaveMessageAsMarkdown(arg1) {
  return window['go']['desktop']['App']['SaveMessageAsMarkdown'](arg1);
}

export function SaveProjectActiveSession(arg1, arg2) {
  return window['go']['desktop']['App']['SaveProjectActiveSession'](arg1, arg2);
}

export function SaveProjectSwitchState(arg1) {
  return window['go']['desktop']['App']['SaveProjectSwitchState'](arg1);
}

export function SaveProjectUIState(arg1) {
  return window['go']['desktop']['App']['SaveProjectUIState'](arg1);
}

export function SaveReviewFileComment(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['SaveReviewFileComment'](arg1, arg2, arg3);
}

export function SaveReviewGeneralComment(arg1, arg2) {
  return window['go']['desktop']['App']['SaveReviewGeneralComment'](arg1, arg2);
}

export function SaveReviewHunkComment(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['SaveReviewHunkComment'](arg1, arg2, arg3, arg4);
}

export function SaveReviewPrompt(arg1) {
  return window['go']['desktop']['App']['SaveReviewPrompt'](arg1);
}

export function SearchBlackboardStepOutputs(arg1, arg2) {
  return window['go']['desktop']['App']['SearchBlackboardStepOutputs'](arg1, arg2);
}

export function SearchVectorStore(arg1) {
  return window['go']['desktop']['App']['SearchVectorStore'](arg1);
}

export function SendMessage(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['desktop']['App']['SendMessage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function SetActiveResearch(arg1, arg2) {
  return window['go']['desktop']['App']['SetActiveResearch'](arg1, arg2);
}

export function SetHypothesisPinned(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['SetHypothesisPinned'](arg1, arg2, arg3, arg4);
}

export function SetLogLevel(arg1) {
  return window['go']['desktop']['App']['SetLogLevel'](arg1);
}

export function SetModelConfig(arg1, arg2) {
  return window['go']['desktop']['App']['SetModelConfig'](arg1, arg2);
}

export function SetResearchPinned(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['SetResearchPinned'](arg1, arg2, arg3);
}

export function SetReviewStatus(arg1, arg2) {
  return window['go']['desktop']['App']['SetReviewStatus'](arg1, arg2);
}

export function SetUpdateSettings(arg1) {
  return window['go']['desktop']['App']['SetUpdateSettings'](arg1);
}

export function SetWailsLogger(arg1) {
  return window['go']['desktop']['App']['SetWailsLogger'](arg1);
}

export function SkipVersion(arg1) {
  return window['go']['desktop']['App']['SkipVersion'](arg1);
}

export function StageAll() {
  return window['go']['desktop']['App']['StageAll']();
}

export function StageFile(arg1) {
  return window['go']['desktop']['App']['StageFile'](arg1);
}

export function StartTerminal(arg1) {
  return window['go']['desktop']['App']['StartTerminal'](arg1);
}

export function StartTerminalInDir(arg1, arg2) {
  return window['go']['desktop']['App']['StartTerminalInDir'](arg1, arg2);
}

export function StashCreate(arg1) {
  return window['go']['desktop']['App']['StashCreate'](arg1);
}

export function StashDrop(arg1) {
  return window['go']['desktop']['App']['StashDrop'](arg1);
}

export function StashList() {
  return window['go']['desktop']['App']['StashList']();
}

export function StashPop(arg1) {
  return window['go']['desktop']['App']['StashPop'](arg1);
}

export function StopTerminal(arg1) {
  return window['go']['desktop']['App']['StopTerminal'](arg1);
}

export function SwitchProject(arg1) {
  return window['go']['desktop']['App']['SwitchProject'](arg1);
}

export function TerminalInput(arg1, arg2) {
  return window['go']['desktop']['App']['TerminalInput'](arg1, arg2);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TrustGitRepo(arg1) {
  return window['go']['desktop']['App']['TrustGitRepo'](arg1);
}

export function UnstageAll() {
  return window['go']['desktop']['App']['UnstageAll']();
}

export function UnstageFile(arg1) {
  return window['go']['desktop']['App']['UnstageFile'](arg1);
}

export function UnwatchDirectory(arg1) {
  return window['go']['desktop']['App']['UnwatchDirectory'](arg1);
}

export function UpdateExperimentalFeatures(arg1) {
  return window['go']['desktop']['App']['UpdateExperimentalFeatures'](arg1);
}

export function UpdateHypothesis(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['UpdateHypothesis'](arg1, arg2, arg3, arg4);
}

export function UpdateLLMConfig(arg1) {
  return window['go']['desktop']['App']['UpdateLLMConfig'](arg1);
}

export function UpdateMCPServers(arg1) {
  return window['go']['desktop']['App']['UpdateMCPServers'](arg1);
}

export function UpdateProxySettings(arg1) {
  return window['go']['desktop']['App']['UpdateProxySettings'](arg1);
}

export function UpdateSearchSettings(arg1) {
  return window['go']['desktop']['App']['UpdateSearchSettings'](arg1);
}

export function UpdateSecuritySettings(arg1) {
  return window['go']['desktop']['App']['UpdateSecuritySettings'](arg1);
}

export function UpdateSmallLLMConfig(arg1) {
  return window['go']['desktop']['App']['UpdateSmallLLMConfig'](arg1);
}

export function UpdateWorkDirectoryDescription(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['UpdateWorkDirectoryDescription'](arg1, arg2, arg3, arg4);
}

export function WatchDirectory(arg1) {
  return window['go']['desktop']['App']['WatchDirectory'](arg1);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['WriteFile'](arg1, arg2, arg3);
}
