package vectorindex

import (
	"strings"
	"testing"
)

func disabledFilter() ContentFilterConfig {
	cfg := DefaultContentFilterConfig()
	cfg.Enabled = false
	return cfg
}

func TestDetectContentSkip_GeneratedHeader(t *testing.T) {
	cfg := DefaultContentFilterConfig()
	content := []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\n// source: foo.proto\n\npackage foo\n")
	reason, skip := DetectContentSkip(content, cfg)
	if !skip || reason != ContentSkipGenerated {
		t.Fatalf("generated header: got skip=%v reason=%q, want true %q", skip, reason, ContentSkipGenerated)
	}
}

func TestDetectContentSkip_GeneratedMarkerBeyondHeaderNotSkipped(t *testing.T) {
	cfg := DefaultContentFilterConfig()
	// The marker sits past the 2 KiB header window: a legitimate file that
	// merely DISCUSSES generated code must not be skipped.
	pad := []byte(strings.Repeat("package main\n\nfunc F%d() {}\n\n", 128))
	content := append([]byte{}, pad...)
	content = append(content, []byte("// see docs: code generated files should be reviewed\n")...)
	reason, skip := DetectContentSkip(content, cfg)
	if skip {
		t.Fatalf("marker beyond header window must not skip (reason %q)", reason)
	}
}

func TestDetectContentSkip_LegitimateFilesNotSkipped(t *testing.T) {
	cfg := DefaultContentFilterConfig()
	files := map[string]string{
		"normal go":     "package main\n\nimport \"fmt\"\n\nfunc main() { fmt.Println(\"hello\") }\n",
		"long prose md": strings.Repeat("Paragraph with normal words and spaces.\n\n", 400),
		"yaml config":   strings.Repeat("key: value\nnested:\n  a: 1\n  b: 2\n", 300),
	}
	for name, body := range files {
		if reason, skip := DetectContentSkip([]byte(body), cfg); skip {
			t.Errorf("%s: unexpected skip with reason %q", name, reason)
		}
	}
}

func TestDetectContentSkip_Minified(t *testing.T) {
	cfg := DefaultContentFilterConfig()
	// Single line, > MinifiedMaxLineBytes, > MinifiedMinBytes, no whitespace.
	body := "var a=1;" + strings.Repeat("(function(){a++})();", 1200)
	reason, skip := DetectContentSkip([]byte(body), cfg)
	if !skip || reason != ContentSkipMinified {
		t.Fatalf("minified: got skip=%v reason=%q, want true %q", skip, reason, ContentSkipMinified)
	}

	// Below the minimum size: a one-liner golf script must not be skipped.
	small := "var a=1;" + strings.Repeat("(function(){a++})();", 10)
	if reason, skip := DetectContentSkip([]byte(small), cfg); skip {
		t.Fatalf("small one-liner must not skip (reason %q)", reason)
	}

	// Long lines but high whitespace ratio (pretty-printed bundle): not minified.
	pretty := strings.Repeat(strings.Repeat("    very padded line with many spaces here;\n", 64), 8)
	if reason, skip := DetectContentSkip([]byte(pretty), cfg); skip {
		t.Fatalf("high-whitespace long file must not skip (reason %q)", reason)
	}
}

func TestDetectContentSkip_PathologicalToken(t *testing.T) {
	cfg := DefaultContentFilterConfig()
	// A file whose overall whitespace ratio stays well above the minified
	// threshold (so the minified rule does not fire) but which contains one
	// unbroken token longer than PathologicalMaxTokenBytes — e.g. a data
	// export with an embedded base64 blob. The file must exceed
	// PathologicalMinBytes.
	var b strings.Builder
	for range 700 {
		b.WriteString("some padded words with plenty of spaces between them here\n")
	}
	b.WriteString(`{"data":"`)
	b.WriteString(strings.Repeat("QUJD", 8192)) // 32 KiB unbroken token
	b.WriteString(`"}\n`)
	for range 700 {
		b.WriteString("more padded words with plenty of spaces between them here\n")
	}
	reason, skip := DetectContentSkip([]byte(b.String()), cfg)
	if !skip || reason != ContentSkipPathological {
		t.Fatalf("pathological: got skip=%v reason=%q, want true %q", skip, reason, ContentSkipPathological)
	}

	// Same blob below the minimum file size: not pathological.
	small := `{"data":"` + strings.Repeat("QUJD", 64) + `"}`
	if reason, skip := DetectContentSkip([]byte(small), cfg); skip {
		t.Fatalf("small blob must not skip (reason %q)", reason)
	}
}

func TestDetectContentSkip_Toggles(t *testing.T) {
	generated := []byte("// Code generated by tool. DO NOT EDIT.\npackage x\n")
	minified := []byte("var a=1;" + strings.Repeat("(function(){a++})();", 1200))

	cfg := DefaultContentFilterConfig()
	cfg.DetectGenerated = false
	if reason, skip := DetectContentSkip(generated, cfg); skip {
		t.Fatalf("detect_generated=false must not skip generated file (reason %q)", reason)
	}

	cfg = DefaultContentFilterConfig()
	cfg.DetectMinified = false
	if reason, skip := DetectContentSkip(minified, cfg); skip {
		t.Fatalf("detect_minified=false must not skip minified file (reason %q)", reason)
	}

	cfg = disabledFilter()
	if reason, skip := DetectContentSkip(generated, cfg); skip {
		t.Fatalf("enabled=false must not skip anything (reason %q)", reason)
	}
}

func TestDetectContentSkip_ThresholdsAreTunable(t *testing.T) {
	body := []byte("var a=1;" + strings.Repeat("(function(){a++})();", 1200))
	loose := DefaultContentFilterConfig()
	loose.MinifiedMaxLineBytes = len(body) + 1 // threshold above the line length
	if reason, skip := DetectContentSkip(body, loose); skip {
		t.Fatalf("raised max-line threshold must not skip (reason %q)", reason)
	}
	tight := DefaultContentFilterConfig()
	tight.MinifiedMinBytes = len(body) + 1
	if reason, skip := DetectContentSkip(body, tight); skip {
		t.Fatalf("raised min-bytes threshold must not skip (reason %q)", reason)
	}
}

func TestDetectContentSkip_Deterministic(t *testing.T) {
	cfg := DefaultContentFilterConfig()
	body := []byte("var a=1;" + strings.Repeat("(function(){a++})();", 1200))
	firstReason, first := DetectContentSkip(body, cfg)
	for range 16 {
		reason, skip := DetectContentSkip(body, cfg)
		if skip != first || reason != firstReason {
			t.Fatalf("non-deterministic verdict: %v/%q vs %v/%q", skip, reason, first, firstReason)
		}
	}
}

func TestContentFilterConfig_Fingerprint(t *testing.T) {
	base := DefaultContentFilterConfig()
	if base.Fingerprint() == "" {
		t.Fatal("fingerprint must not be empty")
	}

	// Every decision-affecting input changes the fingerprint.
	mutations := map[string]func(*ContentFilterConfig){
		"enabled":      func(c *ContentFilterConfig) { c.Enabled = false },
		"generated":    func(c *ContentFilterConfig) { c.DetectGenerated = false },
		"minified":     func(c *ContentFilterConfig) { c.DetectMinified = false },
		"pathological": func(c *ContentFilterConfig) { c.DetectPathological = false },
		"header bytes": func(c *ContentFilterConfig) { c.GeneratedHeaderBytes++ },
		"min bytes":    func(c *ContentFilterConfig) { c.MinifiedMinBytes++ },
		"max line":     func(c *ContentFilterConfig) { c.MinifiedMaxLineBytes++ },
		"ws ratio":     func(c *ContentFilterConfig) { c.MinifiedMaxWhitespaceRatio += 0.01 },
		"path bytes":   func(c *ContentFilterConfig) { c.PathologicalMinBytes++ },
		"max token":    func(c *ContentFilterConfig) { c.PathologicalMaxTokenBytes++ },
	}
	baseFP := base.Fingerprint()
	for name, mutate := range mutations {
		variant := base
		mutate(&variant)
		if variant.Fingerprint() == baseFP {
			t.Errorf("mutation %q did not change the fingerprint", name)
		}
	}

	// Identical configs produce identical fingerprints.
	same := DefaultContentFilterConfig()
	if same.Fingerprint() != baseFP {
		t.Fatal("identical configs must fingerprint identically")
	}
}

// TestChunkerFingerprint_AcceptanceCriteria pins the step's acceptance
// criteria at the fingerprint level: chunk size changes, overlap changes, and
// content-policy changes each produce a different fingerprint, while equal
// inputs stay stable.
func TestChunkerFingerprint_AcceptanceCriteria(t *testing.T) {
	policyA := DefaultContentFilterConfig().Fingerprint()
	policyB := disabledFilter().Fingerprint()

	base := ChunkerFingerprint(1500, 200, policyA)
	if base == "" {
		t.Fatal("fingerprint must not be empty")
	}
	if ChunkerFingerprint(1500, 200, policyA) != base {
		t.Fatal("fingerprint must be stable for identical inputs")
	}
	if ChunkerFingerprint(1400, 200, policyA) == base {
		t.Error("chunk-size change must change the fingerprint")
	}
	if ChunkerFingerprint(1500, 150, policyA) == base {
		t.Error("overlap change must change the fingerprint")
	}
	if ChunkerFingerprint(1500, 200, policyB) == base {
		t.Error("content-policy change must change the fingerprint")
	}
}
