package vectorindex

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
)

func generatedGoSource(padLines int) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by counterfeiter. DO NOT EDIT.\n\npackage mocks\n\n")
	for i := range padLines {
		b.WriteString("func (m *Thing) Method" + itoa(i) + "() int { return m.returns }\n\n")
	}
	return []byte(b.String())
}

func minifiedJSSource(repeat int) []byte {
	var b strings.Builder
	b.WriteString("var a=1;")
	for range repeat {
		b.WriteString("(function(){a++})();")
	}
	return []byte(b.String())
}

// disabledFilterPtr returns a pointer to the default config with the master
// switch off — the explicit opt-out operators can set via
// vector_index.content_filter.enabled: false.
func disabledFilterPtr() *ContentFilterConfig {
	cfg := disabledFilter()
	return &cfg
}

func TestProcessFile_SkipsGeneratedFile(t *testing.T) {
	svc := setupTestService(t)
	t.Cleanup(func() { _ = svc.Close() })
	indexer := NewIndexer(IndexerConfig{Service: svc, ChunkFn: fakeChunkFunc, HashFn: fakeHashFunc})

	root := t.TempDir()
	genPath := filepath.Join(root, "mocks_thing.go")
	if err := os.WriteFile(genPath, generatedGoSource(8), 0o644); err != nil {
		t.Fatal(err)
	}
	vecDocs, lexDocs, err := indexer.processFile(genPath)
	if err != nil {
		t.Fatalf("processFile: %v", err)
	}
	if len(vecDocs) != 0 || len(lexDocs) != 0 {
		t.Fatalf("generated file must produce no documents, got %d vec / %d lex", len(vecDocs), len(lexDocs))
	}

	// Explicit opt-out restores indexing of the same file.
	indexerOptOut := NewIndexer(IndexerConfig{
		Service:       svc,
		ChunkFn:       fakeChunkFunc,
		HashFn:        fakeHashFunc,
		ContentFilter: disabledFilterPtr(),
	})
	vecDocs, lexDocs, err = indexerOptOut.processFile(genPath)
	if err != nil {
		t.Fatalf("processFile (opt-out): %v", err)
	}
	if len(vecDocs) == 0 || len(lexDocs) == 0 {
		t.Fatal("content_filter.enabled=false must index the generated file")
	}
}

// TestIndexFull_FilteredFilesNeverEmbedded proves end-to-end that filtered
// files never reach the embedder while legitimate files are still indexed.
func TestIndexFull_FilteredFilesNeverEmbedded(t *testing.T) {
	var embedCalls atomic.Int64
	counting := func(ctx context.Context, text string) ([]float32, error) {
		embedCalls.Add(1)
		return fakeEmbeddingFunc()(ctx, text)
	}
	svc, err := NewService(ServiceConfig{EmbeddingFunc: counting})
	if err != nil {
		t.Fatalf("NewService: %v", err)
	}
	if err := svc.SetProject("cf-embed-test", t.TempDir()); err != nil {
		t.Fatalf("SetProject: %v", err)
	}
	if err := svc.SwitchBranch(context.Background(), "main"); err != nil {
		t.Fatalf("SwitchBranch: %v", err)
	}
	t.Cleanup(func() { _ = svc.Close() })

	indexer := NewIndexer(IndexerConfig{Service: svc, ChunkFn: fakeChunkFunc, HashFn: fakeHashFunc})

	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "main.go"), []byte("package main\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "mocks_gen.go"), generatedGoSource(8), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "bundle.min.js"), minifiedJSSource(1200), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := indexer.IndexFull(context.Background(), root); err != nil {
		t.Fatalf("IndexFull: %v", err)
	}

	// fakeChunkFunc yields exactly one chunk per non-empty file that reaches
	// it; only main.go may reach the embedder.
	if calls := embedCalls.Load(); calls != 1 {
		t.Errorf("embedder called %d times; want exactly 1 (legitimate file only)", calls)
	}
}

// TestValidateCollection_ContentFilterExcludedAndDeleted pins the incremental
// semantics of the content policy: an excluded file on disk is never "new",
// and a previously-indexed file that the active policy now excludes is
// reported deleted so its documents and sidecar entry are removed.
func TestValidateCollection_ContentFilterExcludedAndDeleted(t *testing.T) {
	ws := t.TempDir()
	proj := t.TempDir()

	// Service created with the filter DISABLED, mirroring a project indexed
	// before the policy was turned on. The sidecar fingerprint records the
	// disabled policy.
	svc, err := NewService(ServiceConfig{
		EmbeddingFunc: fakeEmbeddingFunc(),
		ContentFilter: disabledFilterPtr(),
	})
	if err != nil {
		t.Fatalf("NewService: %v", err)
	}
	t.Cleanup(func() { _ = svc.Close() })
	if err := svc.SetProject("proj-cf", proj); err != nil {
		t.Fatalf("SetProject: %v", err)
	}
	if err := svc.SwitchBranch(context.Background(), "main"); err != nil {
		t.Fatalf("SwitchBranch: %v", err)
	}

	indexer := NewIndexer(IndexerConfig{
		Service:       svc,
		ChunkFn:       fakeChunkFunc,
		ContentFilter: disabledFilterPtr(),
	})

	genFile := filepath.Join(ws, "mocks_gen.go")
	if err := os.WriteFile(genFile, generatedGoSource(8), 0o644); err != nil {
		t.Fatal(err)
	}
	legitFile := filepath.Join(ws, "main.go")
	if err := os.WriteFile(legitFile, []byte("package main\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := indexer.IndexFull(context.Background(), ws); err != nil {
		t.Fatalf("IndexFull: %v", err)
	}

	// Sanity: with the filter off, both files were indexed.
	svc.mu.RLock()
	_, genIndexed := svc.current.fileHashes[genFile]
	_, legitIndexed := svc.current.fileHashes[legitFile]
	svc.mu.RUnlock()
	if !genIndexed || !legitIndexed {
		t.Fatalf("filter-off pass must index both files: gen=%v legit=%v", genIndexed, legitIndexed)
	}

	// A newly-created excluded file is never reported as new.
	newMin := filepath.Join(ws, "bundle.min.js")
	if err := os.WriteFile(newMin, minifiedJSSource(1200), 0o644); err != nil {
		t.Fatal(err)
	}

	// Flip the active policy to the default (enabled). The fingerprint
	// changes with it, exactly like a vector_index.content_filter change in
	// production wiring (NewManager derives both from the same resolved
	// config).
	svc.mu.Lock()
	enabled := DefaultContentFilterConfig()
	svc.contentFilter = enabled
	svc.chunkerFingerprint = ChunkerFingerprint(DefaultMaxChunkSize, DefaultChunkOverlap, enabled.Fingerprint())
	svc.mu.Unlock()

	// A policy change invalidates the fingerprint of EVERY sidecar entry
	// (the policy participates in it), so the legitimate file is reported
	// stale for re-chunking — its identical chunks then hit the
	// content-addressed embedding cache — while the now-excluded generated
	// file is reported deleted because validation does not mark it seen.
	stale, newFiles, deleted, valErr := svc.ValidateCollection(context.Background(), ws, testIgnoreChecker(t, ws))
	if valErr != nil {
		t.Fatalf("ValidateCollection: %v", valErr)
	}
	for _, f := range newFiles {
		if f == newMin {
			t.Fatalf("excluded file %q must not be reported new", newMin)
		}
	}
	if len(stale) != 1 || stale[0] != legitFile {
		t.Fatalf("legitimate file must be reported stale after policy change, got %v", stale)
	}
	if len(deleted) != 1 || deleted[0] != genFile {
		t.Fatalf("previously-indexed generated file must be reported deleted, got %v", deleted)
	}

	// After the incremental pass reconciles the deletion, a follow-up pass is
	// stable: no churn.
	if err := indexer.IndexIncremental(context.Background(), ws); err != nil {
		t.Fatalf("IndexIncremental: %v", err)
	}

	stale, newFiles, deleted, valErr = svc.ValidateCollection(context.Background(), ws, testIgnoreChecker(t, ws))
	if valErr != nil {
		t.Fatalf("follow-up ValidateCollection: %v", valErr)
	}
	if len(stale) != 0 || len(newFiles) != 0 || len(deleted) != 0 {
		t.Fatalf("follow-up pass must be stable: stale=%v new=%v deleted=%v", stale, newFiles, deleted)
	}
}

// TestNewManager_ContentFilterWiring pins that ManagerConfig.ContentFilter
// reaches both the Service (validation semantics) and the per-project Indexer
// (chunk-time semantics), and that the default fingerprint embeds the default
// policy.
func TestNewManager_ContentFilterWiring(t *testing.T) {
	mgr, err := NewManager(ManagerConfig{EmbeddingFunc: fakeEmbeddingFunc()})
	if err != nil {
		t.Fatalf("NewManager: %v", err)
	}
	t.Cleanup(func() { mgr.Shutdown() })

	want := DefaultContentFilterConfig()
	if mgr.contentFilter != want {
		t.Errorf("default Manager contentFilter = %+v, want %+v", mgr.contentFilter, want)
	}
	if mgr.service.contentFilter != want {
		t.Errorf("default Service contentFilter = %+v, want %+v", mgr.service.contentFilter, want)
	}
	wantFP := ChunkerFingerprint(DefaultMaxChunkSize, DefaultChunkOverlap, want.Fingerprint())
	if mgr.service.chunkerFingerprint != wantFP {
		t.Errorf("default fingerprint = %q, want %q (must embed the default content policy)", mgr.service.chunkerFingerprint, wantFP)
	}

	custom := disabledFilter()
	mgrCustom, err := NewManager(ManagerConfig{
		EmbeddingFunc: fakeEmbeddingFunc(),
		ContentFilter: &custom,
	})
	if err != nil {
		t.Fatalf("NewManager (custom): %v", err)
	}
	t.Cleanup(func() { mgrCustom.Shutdown() })
	if mgrCustom.contentFilter.Enabled {
		t.Error("custom disabled filter must reach the Manager")
	}
	if mgrCustom.service.contentFilter.Enabled {
		t.Error("custom disabled filter must reach the Service")
	}
	if mgrCustom.service.chunkerFingerprint == wantFP {
		t.Error("policy change must change the Manager fingerprint")
	}
}
