package vectorindex

import (
	"fmt"
	"math"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/v0lka/sp4rk/embedding"
)

// This file is the retrieval-quality gate for chunking defaults. It builds a
// deterministic corpus (fixed templates, no randomness, no repository
// files, no ONNX), chunks it with candidate configurations, embeds chunks
// with a deterministic token-hash embedder, and measures:
//
//   - MRR and Recall@3 over queries whose related tokens live near chunk
//     boundaries (the geometry overlap exists to protect), and
//   - total chunks, unique chunks (what the content-addressed embedding
//     cache deduplicates to), and the implied ONNX inference count
//     (ceil(unique / DefaultEmbeddingBatchSize)).
//
// The corpus includes generated and minified files so the gate also proves
// the content filter reduces unique chunks (and therefore inferences)
// without touching retrieval of legitimate content.

const (
	qualityDim           = 256
	qualityQueryDeadline = 10 // ranks beyond this count as a miss
	// defaultQualityTokenizerPath is the bundled tokenizer asset fetched by
	// make fetch-embedding-model; used by the truncation audit when the
	// EMBEDDING_TEST_TOKENIZER_PATH override is unset.
	defaultQualityTokenizerPath = ".cache/models/jina-v2-small-tokenizer.json"
)

type qualityFile struct {
	name    string
	content string
	queries []qualityQuery
}

type qualityQuery struct {
	related []string // tokens sprinkled inside the target section
	anchor  string   // unique token identifying the target section
}

type qualityReport struct {
	maxSize   int
	overlap   int
	filterOn  bool
	mrr       float64
	recallAt3 float64
	chunks    int
	unique    int
	infer     int
}

func buildQualityCorpus() []qualityFile {
	sizes := []int{600, 1200, 1900, 2600, 3400, 4400}
	fillers := []string{
		"value", "result", "state", "handle", "process", "update",
		"entry", "buffer", "worker", "config",
	}
	newSection := func(anchor string, related []string, target int, goStyle bool, idx int) string {
		var b strings.Builder
		if goStyle {
			fmt.Fprintf(&b, "// section %s begin\n", anchor)
		} else {
			fmt.Fprintf(&b, "## Section %s\n\n", anchor)
		}
		lineBudget := target / 28
		for i := 0; i < lineBudget; i++ {
			switch {
			case i == lineBudget/8:
				fmt.Fprintf(&b, "// %s marker %s\n", related[0], fillers[idx%len(fillers)])
			case i == lineBudget/2:
				fmt.Fprintf(&b, "// %s checkpoint %s\n", related[1], fillers[(idx+1)%len(fillers)])
			case i == lineBudget*3/4:
				fmt.Fprintf(&b, "// %s boundary %s\n", related[2], fillers[(idx+2)%len(fillers)])
			case goStyle:
				fmt.Fprintf(&b, "\tf%d := compute(%s, %s)\n\t_ = f%d\n", i, fillers[i%len(fillers)], fillers[(i+3)%len(fillers)], i)
			default:
				fmt.Fprintf(&b, "The %s step records the %s into the %s ledger.\n", fillers[i%len(fillers)], fillers[(i+1)%len(fillers)], fillers[(i+2)%len(fillers)])
			}
		}
		if goStyle {
			b.WriteString("// section end\n\n")
		} else {
			b.WriteString("\n")
		}
		return b.String()
	}

	files := make([]qualityFile, 0, 14) // 8 Go + 4 Markdown + 2 noise files
	idx := 0
	for fi := range 8 {
		var b strings.Builder
		queries := make([]qualityQuery, 0, len(sizes))
		fmt.Fprintf(&b, "package qpkg%d\n\nimport \"fmt\"\n\n", fi)
		for si := range len(sizes) {
			anchor := fmt.Sprintf("qanchor%d_%d", fi, si)
			related := []string{
				fmt.Sprintf("qrw%d_%da", fi, si),
				fmt.Sprintf("qrw%d_%db", fi, si),
				fmt.Sprintf("qrw%d_%dc", fi, si),
			}
			b.WriteString(newSection(anchor, related, sizes[si], true, idx))
			queries = append(queries, qualityQuery{related: related, anchor: anchor})
			idx++
		}
		files = append(files, qualityFile{name: fmt.Sprintf("q%d.go", fi), content: b.String(), queries: queries})
	}
	for mi := range 4 {
		var b strings.Builder
		queries := make([]qualityQuery, 0, len(sizes))
		fmt.Fprintf(&b, "# Document %d\n\n", mi)
		for si := range len(sizes) {
			anchor := fmt.Sprintf("qanchorm%d_%d", mi, si)
			related := []string{
				fmt.Sprintf("qrwm%d_%da", mi, si),
				fmt.Sprintf("qrwm%d_%db", mi, si),
				fmt.Sprintf("qrwm%d_%dc", mi, si),
			}
			b.WriteString(newSection(anchor, related, sizes[(si+2)%len(sizes)], false, idx))
			queries = append(queries, qualityQuery{related: related, anchor: anchor})
			idx++
		}
		files = append(files, qualityFile{name: fmt.Sprintf("doc%d.md", mi), content: b.String(), queries: queries})
	}

	// Generated + minified noise: never retrieval targets; must be excluded
	// by the default content filter so they contribute zero chunks.
	files = append(files,
		qualityFile{name: "mock_gen.go", content: "// Code generated bymockgen. DO NOT EDIT.\n\npackage mocks\n\n" + strings.Repeat("func M() {}\n\n", 200)},
		qualityFile{name: "bundle.min.js", content: "var a=1;" + strings.Repeat("(function(){a++})();", 1400)},
	)
	return files
}

func qualityEmbed(text string) []float64 {
	vec := make([]float64, qualityDim)
	for _, tok := range strings.FieldsFunc(strings.ToLower(text), func(r rune) bool {
		isLower := r >= 'a' && r <= 'z'
		isDigit := r >= '0' && r <= '9'
		return !isLower && !isDigit
	}) {
		h := uint32(2166136261)
		for _, c := range tok {
			h ^= uint32(c)
			h *= 16777619
		}
		vec[h%qualityDim]++
	}
	var norm float64
	for _, v := range vec {
		norm += v * v
	}
	if norm == 0 {
		return vec
	}
	for i := range vec {
		vec[i] /= math.Sqrt(norm)
	}
	return vec
}

func cosine(a, b []float64) float64 {
	var dot float64
	for i := range a {
		dot += a[i] * b[i]
	}
	return dot
}

// evaluateQualityCorpus chunks the corpus under one configuration and
// returns the retrieval metrics plus the workload counters.
func evaluateQualityCorpus(t *testing.T, maxSize, overlap int, filter ContentFilterConfig) qualityReport {
	t.Helper()
	corpus := buildQualityCorpus()

	type chunkRef struct {
		content string
		vec     []float64
	}
	var chunks []chunkRef
	unique := make(map[string]struct{})
	for _, f := range corpus {
		if _, skip := DetectContentSkip([]byte(f.content), filter); skip {
			continue
		}
		parsed, err := embedding.ChunkFile("/"+f.name, []byte(f.content), embedding.ChunkerConfig{
			MaxChunkSize: maxSize,
			Overlap:      overlap,
		})
		if err != nil {
			t.Fatalf("ChunkFile(%s): %v", f.name, err)
		}
		for _, c := range parsed {
			chunks = append(chunks, chunkRef{content: c.Content, vec: qualityEmbed(c.Content)})
			unique[c.Content] = struct{}{}
		}
	}
	for i := range chunks {
		if len(chunks[i].vec) != qualityDim {
			t.Fatalf("chunk %d embedding dimension mismatch", i)
		}
	}

	var mrr, recallAt3 float64
	queryCount := 0
	for _, f := range corpus {
		for _, q := range f.queries {
			queryCount++
			qvec := qualityEmbed(strings.Join(q.related, " "))
			type scored struct {
				score float64
				ref   chunkRef
			}
			ranked := make([]scored, 0, len(chunks))
			for _, c := range chunks {
				ranked = append(ranked, scored{score: cosine(qvec, c.vec), ref: c})
			}
			sort.SliceStable(ranked, func(i, j int) bool {
				return ranked[i].score > ranked[j].score
			})
			rank := -1
			for i := 0; i < len(ranked) && i < qualityQueryDeadline; i++ {
				if strings.Contains(ranked[i].ref.content, q.anchor) {
					rank = i + 1
					break
				}
			}
			if rank > 0 {
				mrr += 1 / float64(rank)
				if rank <= 3 {
					recallAt3++
				}
			}
		}
	}
	mrr /= float64(queryCount)
	recallAt3 /= float64(queryCount)
	infer := (len(unique) + DefaultEmbeddingBatchSize - 1) / DefaultEmbeddingBatchSize
	return qualityReport{
		maxSize:   maxSize,
		overlap:   overlap,
		filterOn:  filter.Enabled,
		mrr:       mrr,
		recallAt3: recallAt3,
		chunks:    len(chunks),
		unique:    len(unique),
		infer:     infer,
	}
}

// truncationAudit measures, with the REAL production tokenizer when the
// bundled asset is available, the share of corpus chunks whose token length
// reaches the model's MaxSeqLength (512) — i.e. chunks the embedder would
// truncate, silently losing tail content from the vector. A chunk-size
// candidate that increases this share degrades real retrieval quality even
// when the synthetic embedder above cannot see it. Returns ok=false when the
// tokenizer asset is unavailable (the audit then skips, like the ONNX
// benchmarks).
func truncationAudit(t *testing.T, maxSize, overlap int) (truncatedShare float64, ok bool) {
	t.Helper()
	path := os.Getenv("EMBEDDING_TEST_TOKENIZER_PATH")
	if path == "" {
		for _, candidate := range []string{
			defaultQualityTokenizerPath,
			"../../" + defaultQualityTokenizerPath, // package-dir test CWD → repo root
		} {
			if _, err := os.Stat(candidate); err == nil {
				path = candidate
				break
			}
		}
	}
	if path == "" {
		return 0, false
	}
	tk, err := embedding.NewTokenizer(path)
	if err != nil {
		return 0, false
	}
	filterOn := DefaultContentFilterConfig()
	corpus := buildQualityCorpus()
	total, truncated := 0, 0
	for _, f := range corpus {
		if _, skip := DetectContentSkip([]byte(f.content), filterOn); skip {
			continue
		}
		parsed, perr := embedding.ChunkFile("/"+f.name, []byte(f.content), embedding.ChunkerConfig{
			MaxChunkSize: maxSize,
			Overlap:      overlap,
		})
		if perr != nil {
			t.Fatalf("ChunkFile(%s): %v", f.name, perr)
		}
		for _, c := range parsed {
			// The pinned sp4rk version exposes Encode (padded/truncated to
			// maxLen with an attention mask); counting attended positions
			// yields the actual length without the newer EncodeWithLength.
			_, mask, _, eerr := tk.Encode(c.Content, 512)
			if eerr != nil {
				t.Fatalf("Encode: %v", eerr)
			}
			total++
			actualLen := 0
			for _, m := range mask {
				if m == 1 {
					actualLen++
				}
			}
			if actualLen >= 512 {
				truncated++
			}
		}
	}
	if total == 0 {
		return 0, true
	}
	return float64(truncated) / float64(total), true
}

// TestRetrievalQualityGate_Defaults is the acceptance gate for chunking
// defaults. The historical baseline is (1500, 200) with the content filter
// on. The shipped defaults must:
//
//  1. not degrade MRR or Recall@3 against the baseline (tolerance 0.005), and
//  2. not increase the unique-chunk count (the inference workload after
//     cache deduplication), and
//  3. the content filter must strictly reduce unique chunks versus the same
//     chunking with the filter off (generated/minified noise excluded).
//
// If a future default change violates (1) or (2), the change must be
// reverted or re-validated — the gate exists precisely so defaults cannot
// drift into silently worse retrieval or more inferences.
func TestRetrievalQualityGate_Defaults(t *testing.T) {
	filterOn := DefaultContentFilterConfig()
	baseline := evaluateQualityCorpus(t, 1500, 200, filterOn)
	current := evaluateQualityCorpus(t, DefaultMaxChunkSize, DefaultChunkOverlap, filterOn)

	t.Logf("baseline (1500,200,filter): mrr=%.4f r@3=%.4f chunks=%d unique=%d infer=%d",
		baseline.mrr, baseline.recallAt3, baseline.chunks, baseline.unique, baseline.infer)
	t.Logf("defaults (%d,%d,filter):    mrr=%.4f r@3=%.4f chunks=%d unique=%d infer=%d",
		current.maxSize, current.overlap, current.mrr, current.recallAt3, current.chunks, current.unique, current.infer)

	if current.mrr < baseline.mrr-0.005 {
		t.Errorf("default chunking degrades MRR: %.4f < %.4f", current.mrr, baseline.mrr)
	}
	if current.recallAt3 < baseline.recallAt3-0.005 {
		t.Errorf("default chunking degrades Recall@3: %.4f < %.4f", current.recallAt3, baseline.recallAt3)
	}
	if current.unique > baseline.unique {
		t.Errorf("default chunking increases unique chunks: %d > %d", current.unique, baseline.unique)
	}
	if current.infer > baseline.infer {
		t.Errorf("default chunking increases implied inferences: %d > %d", current.infer, baseline.infer)
	}

	filterOff := filterOn
	filterOff.Enabled = false
	unfiltered := evaluateQualityCorpus(t, DefaultMaxChunkSize, DefaultChunkOverlap, filterOff)
	t.Logf("filter OFF:                unique=%d infer=%d", unfiltered.unique, unfiltered.infer)
	if unfiltered.unique <= current.unique {
		t.Errorf("content filter must reduce unique chunks on the corpus: off=%d on=%d", unfiltered.unique, current.unique)
	}

	// Real-tokenizer truncation audit: the defaults must not push a larger
	// share of chunks to the model's 512-token ceiling than the baseline.
	baseTrunc, baseOK := truncationAudit(t, 1500, 200)
	curTrunc, curOK := truncationAudit(t, DefaultMaxChunkSize, DefaultChunkOverlap)
	if baseOK && curOK {
		t.Logf("truncation share: baseline=%.4f defaults=%.4f", baseTrunc, curTrunc)
		if curTrunc > baseTrunc {
			t.Errorf("default chunking increases truncated-chunk share: %.4f > %.4f", curTrunc, baseTrunc)
		}
	} else {
		t.Log("truncation audit skipped: tokenizer asset unavailable")
	}
}

// TestRetrievalQualityGate_CandidateGrid documents the evaluation grid used
// to pick defaults. It logs every candidate's metrics; the assertions only
// pin sanity (deterministic corpus yields stable numbers) so the grid is
// reproducible evidence rather than a silent constant bump.
func TestRetrievalQualityGate_CandidateGrid(t *testing.T) {
	filterOn := DefaultContentFilterConfig()
	candidates := [][2]int{
		{1500, 200}, {1500, 150}, {1500, 100}, {1500, 0},
		{1600, 200}, {1600, 160}, {1800, 200}, {1800, 180},
		{1200, 200}, {1200, 120}, {2000, 200},
	}
	baseline := evaluateQualityCorpus(t, 1500, 200, filterOn)
	baseTrunc, baseOK := truncationAudit(t, 1500, 200)
	for _, c := range candidates {
		rep := evaluateQualityCorpus(t, c[0], c[1], filterOn)
		quality := rep.mrr >= baseline.mrr-0.005 && rep.recallAt3 >= baseline.recallAt3-0.005
		extra := ""
		if baseOK {
			if trunc, ok := truncationAudit(t, c[0], c[1]); ok {
				extra = fmt.Sprintf(" trunc=%.4f", trunc)
				if trunc > baseTrunc {
					quality = false // truncation risk disqualifies the candidate
				}
			}
		}
		t.Logf("candidate (%d,%d): mrr=%.4f r@3=%.4f chunks=%d unique=%d infer=%d qualityOK=%v cheaper=%v%s",
			c[0], c[1], rep.mrr, rep.recallAt3, rep.chunks, rep.unique, rep.infer,
			quality, rep.unique < baseline.unique, extra)
	}
}
